using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TopDownRay : MonoBehaviour
{
    public float moveSpeed = 5f;
    private Rigidbody2D rb;
    private Vector2 moveInput;

    void Awake()
    {
        rb = GetComponent<Rigidbody2D>();
    }

    void Update()
    {
        // basic WASD and arrow inputs
        moveInput.x = Input.GetAxisRaw("Horizontal");
        moveInput.y = Input.GetAxisRaw("Vertical");
        moveInput.Normalize();
    }

    void FixedUpdate()
    {
        // applies velocity
        rb.velocity = moveInput * moveSpeed;
    }
}
